version: '2'

services:
  app2:
    container_name: "app2"
    image: debian:jessie
    command: sleep 1000
    networks:
      custom_network:
        ipv4_address: 192.168.222.10
    external_links:
     - app1

networks:
  custom_network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.222.0/24
        gateway: 192.168.222.1
